### ISSUE TITLE
What should be done with the Baldur's Gate Arms and Armour Emporium (2022 Version 0.9)?

### ISSUE THREAD

**Issue by WithinAmnesia** [GraionDilach/ExtraExpandedEnhancedEncounters#1]
Quote from the Beamdog Forums for simplification:
"Baldur's Gate Arms and Armour Emporium (2022 Version 0.9)

Here is an early release / mostly functional version that has the Baldur's Gate Arms and Armour Emporium working with the merchants and one oversimplified item upgrade recipe for Long Sword +2 'Varscona' -> Long Sword +3 'Varscona'. Some features are not implemented (like calling the guard when getting caught looting in the Emporium). Two of my other minor quests are included such as Hull's Long Sword Extension and Ghost Knights of Ulcaster Quest (mostly to get the stores / items / installer working). I combed through this version to see if any Sea Tower files were in it and made sure to remove any if they existed and to only have my content in the files; although it could not hurt to double check [@jastey](https://forums.beamdog.com/profile/jastey) . I am not 100% sure how to make this module work nicely / play nice with other mods or even if it works with the current E.E.E.E. properly [@GraionDilach](https://forums.beamdog.com/profile/GraionDilach) . I took a fresh S.o.D. game and iterated away until the Arms and Armour Emporium / install worked. If you find any missed bugs please feel free to report them. Feedback is welcome :-).

Download link / mirror (the attached file is the same zip): https://mega.nz/folder/KBYTQIBI#CFhHkRHk6ZyGtsCB334mqA
[Arms and Armour Emporium (2022 Version 0.9).zip](https://github.com/GraionDilach/ExtraExpandedEnhancedEncounters/files/9105788/Arms.and.Armour.Emporium.2022.Version.0.9.zip) " - https://forums.beamdog.com/discussion/comment/1184902/#Comment_1184902

This Baldur's Gate Arms and Armour Emporium version only has the work that pre-dates the SeaTower melt-down / does not include any work from my doomed part with SeaTower project.

I am not sure what to do with this project. @GraionDilach has tinkered with the Drake scales and has also worked on iterating upon my previous work so I had the idea to put this here and see what may come of such a creative invitation. In April of 2022 I tried (hopefully successfully) to assemble / salvage / save my Baldur's Gate Arms and Armour Emporium work for it was very close to being fully functional. It seems like it is currently in a late Alpha or closed Beta kind of state of existence with the 2022 Version 0.9 iteration. It is kind of based upon a sort of waking dream / vision I had / have and I am not the best at translating those kinds of visions into perfectly working / well polished mods / content for the community to hopefully enjoy.

I hope to not be very rigid in my vision / approach with making new content for the inspiration comes to myself in an almost hazy dream like fashion / rampant imagination. Or if I am being completely honest my ~'creative process' can be even be likened to an experience as if a monkey is locked in the control room with the keys XD. Also I like tinkering / modding things from their original 'set up' / configuration or even adding onto what already exists to hopefully creative something new and exciting. So I would find it hypocritical of myself to have complete creative control over something that I wish to ultimately share to the community for many more people to hopefully enjoy.

I find that it feels more of an adventure as well to share and collaborate upon an encouraging dream and see how to grows and evolves and iterates. It is a sort of feeling of understanding that I am trying to communicate that can almost be expressed as in like: To empower only one's self can be in many ways limited in potential; yet to empower all others can be in many ways unlimited in potential.

What may come of this project / work? I am not 100% observant on all details as to what other projects are going on within the Baldur's Gate creative community sphere of influence. Yet I wonder if anyone is interested in this sort of new content / project / mod? If so I wonder who those people are. I kind of wonder what kinds and scopes of new content people would like to see in / with Baldur's Gate and what will happen in the future with the game and its creative community.

P.S. I almost forgot these details: There are a bunch of missing smithing / item upgrade recipes that I am not 100% sure what kind of material / time requirements should be appropriate to reforge / upgrade the plethora of Baldur's Gate's unique magical items into upgrade versions such as in +1 -> +2, +2 -> +3 or in rare / very specific / niche / special cases +4. As in like with Xan's Moonblade +3 -> +4 or Mithril Chain Mail +4 -> +4 with and or added magical once per day / extra passive item abilities. I hope every upgraded item has added magical once per day / extra passive item abilities to make them feel special and not a generic standard +2, +3 or +4 item but something really special. Also I thought maybe to use special unused Faerûn jewels to limit the +3 and +4 items like say there are only x3  in all of the immediate original Baldur's Gate game area (more with BG1+BG2 projects perhaps?) that are hidden in the hardest challenge areas (bottom of Durlag's Tower, added magically / quest sealed Undercity Crypt / Tomb lich boss chamber? An added BG 1 style Dragon *somewhere* etc.)? There are more details / ideas / concepts in the description of this master link: https://www.deviantart.com/withinamnesia/art/Jewels-Emporium-Finished-822805076
Also I attached my BAMs and item work (made into a .zip file) with the Baldur's Gate Jewels (Ruby, Star Ruby, Chardalyn).
[Baldur's-Gate-Jewels.zip](https://github.com/GraionDilach/ExtraExpandedEnhancedEncounters/files/9106135/Baldur.s-Gate-Jewels.zip)

**Comment by GraionDilach** [comment]
Invalid for this repository.
